- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
